[project]
name = "feedsummarizer"
version = "0.1.0"
# Pinned to 3.13 so we stay in line with AWS' Lambda runtime
requires-python = "==3.13"
dependencies = []

[dependency-groups]
dev = [
    "black>=25.1.0",
]
